### ISSUE TITLE
visualization comments

### ISSUE THREAD

**Issue by gregcaporaso** [nbokulich/q2-sample-classifier#10] opened 2017-06-09 23:01 UTC
1. I think these category labels would be a little more clear if they were centered in these plots:

![screenshot 2017-06-09 16 00 15](https://user-images.githubusercontent.com/192372/26997246-de98d4c4-4d2c-11e7-9a18-b62273626f04.png)

2. It looks like there are some ``\n``s in the "parameters" section that are not being interpreted correctly. I think it might be better to not include this parameters section, since all of that information is already in the provenance. 

![screenshot 2017-06-09 16 02 17](https://user-images.githubusercontent.com/192372/26997290-3813ddfa-4d2d-11e7-88d0-16c37867fdc4.png)

3. What do you think of putting a ``tsv`` link after the *Feature Importance* header, rather than after the table? It's easy to not notice if it's way down at the bottom of the page. 

4. The leading zero in these ``regress-*`` visualizations is a little confusing. Could you drop that? (I think it's the index of the dataframe that those results are in.)

![screenshot 2017-06-09 16 25 34](https://user-images.githubusercontent.com/192372/26997678-6bd3ffa0-4d30-11e7-9a44-f9a80be5dcd2.png)

Also, would it be possible to make those column headers more clear (e.g., expand *MSE*, and use *P-value* instead of *P-val*)?

5. Could you change *Accuracy score* to *Overall accuracy*, and put that with the table of per-category accuracies? Especially if you end up removing the parameters section (see my comment 2) this info will be hanging out on it's own and would be a little awkward. In the regress visualizers, I think you could also then drop the MSE (is it the same as the accuracy score?).

**Comment by nbokulich** [comment] 2017-06-17 02:08
>1. I think these category labels would be a little more clear if they were centered in these plots

👍 done

> 2. I think it might be better to not include this parameters section, since all of that information is already in the provenance.

That information is actually NOT all in the provenance, since not all parameters used by the model are user defined... it may not be important to report this information, so we can remove, but what I have done for now is turn this into a pretty table that is moved near the bottom of the visualization. Overall accuracy is now reported in the confusion matrix / regression summary, rather than in this parameter summary.

> 3. What do you think of putting a tsv link after the Feature Importance header

👍 👍 👍 done.

> 4. The leading zero in these regress-* visualizations is a little confusing

I cannot drop this easily... but I have given it a name ("score") to clarify

> 5. Could you change Accuracy score to Overall accuracy

done.

Thanks @gregcaporaso all these changes have now been made — I am closing this issue, but if you get a chance to look over my comments above and want further changes, please reopen.

**Closed by nbokulich** 2017-06-17 02:08 UTC
